version: '2'
volumes:
   myapp:
services:
  myapp:
    volumes:
     - myapp:/app
    image: 'bitnami/codeigniter:3'
    ports:
      - '8000:8000'
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
